package soac.miniprojet.api;
// Generated 7 janv. 2020 11:56:55 by Hibernate Tools 5.4.7.Final

import soac.miniprojet.model.dao.DAO;
import soac.miniprojet.model.dao.DAOInterface;
import soac.miniprojet.model.dao.daos.BiblioInscPeriodDAO;

import java.util.LinkedList;

/**
 * BiblioInscPeriod generated by hbm2java
 */
public class BiblioInscPeriodAPI extends DAO implements DAOInterface {

    BiblioInscPeriodDAO dao;

    @Override
    public Object getById(int id) {

        return dao.getById(id);    }

    @Override
    public boolean deleteById(int id) {

        return  dao.deleteById(id);
    }

    @Override
    public boolean update(Object object) {

        return dao.update(object);
    }

    @Override
    public boolean add(Object object) {

        return dao.add(object);
    }

    @Override
    public LinkedList getAll() {

        return dao.getAll();
    }
    public int countAll() {

        return dao.countAll();
}

}