package soac.miniprojet.api;
// Generated 7 janv. 2020 11:56:55 by Hibernate Tools 5.4.7.Final

import soac.miniprojet.model.dao.DAO;
import soac.miniprojet.model.dao.DAOInterface;
import soac.miniprojet.model.dao.daos.ScholarYearDAO;

import java.util.LinkedList;

/**
 * ScholarYear generated by hbm2java
 */
public class ScholarYearAPI extends DAO implements DAOInterface {

	ScholarYearDAO dao;

	@Override
	public Object getById(int id) {

		return dao.getById(id);

	}

	@Override
	public boolean deleteById(int id) {

		return  dao.deleteById(id,"scholar_year");
	}

    @Override
    public boolean update(Object object) {

		return dao.update(object);

    }


    @Override
	public boolean add(Object object) {

		return dao.add(object);

	}

	@Override
	public LinkedList getAll() {

		return dao.getAll();

	}
	public int countAll() {

		 return dao.countAll();

}
}
