package soac.miniprojet.model.dao.daos;
// Generated 7 janv. 2020 11:56:55 by Hibernate Tools 5.4.7.Final

import soac.miniprojet.model.dao.DAO;
import soac.miniprojet.model.dao.DAOInterface;

import java.util.Date;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.Set;

/**
 * InscriptionPeriod generated by hbm2java
 */
public class InscriptionPeriodDAO extends DAO implements DAOInterface {

	@Override
	public Object getById(int id) {
		return null;
	}

	@Override
	public boolean deleteById(int id) {
		return false;
	}

	@Override
	public boolean update(Object object) {
		return false;
	}

	@Override
	public boolean add(Object object) {
		return false;
	}

	@Override
	public boolean delete(Object object) {
		return false;
	}

	@Override
	public LinkedList getAll() {
		return null;
	}

	@Override
	public int countAll() {
		return 0;
	}
}
