package soac.miniprojet.daos.beans;
// Generated 7 janv. 2020 11:56:55 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * StudentsBiblioInscId generated by hbm2java
 */
public class StudentsBiblioInscId implements java.io.Serializable {

	private int studentId;
	private int scholarYearId;
	private Date dateInsc;

	public StudentsBiblioInscId() {
	}

	public StudentsBiblioInscId(int studentId, int scholarYearId, Date dateInsc) {
		this.studentId = studentId;
		this.scholarYearId = scholarYearId;
		this.dateInsc = dateInsc;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public int getScholarYearId() {
		return this.scholarYearId;
	}

	public void setScholarYearId(int scholarYearId) {
		this.scholarYearId = scholarYearId;
	}

	public Date getDateInsc() {
		return this.dateInsc;
	}

	public void setDateInsc(Date dateInsc) {
		this.dateInsc = dateInsc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentsBiblioInscId))
			return false;
		StudentsBiblioInscId castOther = (StudentsBiblioInscId) other;

		return (this.getStudentId() == castOther.getStudentId())
				&& (this.getScholarYearId() == castOther.getScholarYearId())
				&& ((this.getDateInsc() == castOther.getDateInsc()) || (this.getDateInsc() != null
						&& castOther.getDateInsc() != null && this.getDateInsc().equals(castOther.getDateInsc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudentId();
		result = 37 * result + this.getScholarYearId();
		result = 37 * result + (getDateInsc() == null ? 0 : this.getDateInsc().hashCode());
		return result;
	}

}
